version: "3.3"
services:
  
  postgres:
    container_name: back_postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=back_postgres

    ports:
      - "5432:5432"

  backend:
    build: .
    command: sh -c "python manage.py migrate && gunicorn core.wsgi -b 0.0.0.0:8000"
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=back_postgres
      - DB_USER=postgres
      - DB_PASS=1234

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    # copy data of nginx.conf file to config of nginx on container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

networks:
  main:
