version: "3.3"
services:

  db:
    container_name: back_postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=back_postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    networks:
      - djangonetwork

  backend:
    build: .
    command: sh -c "python manage.py migrate && gunicorn core.wsgi -b 0.0.0.0:8000"
    # command: >
      # sh -c "python manage.py wait_for_db &&
            # python manage.py migrate &&
            # python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=back_postgres
      - DB_USER=postgres
      - DB_PASS=1234
    links:
       - db:db
    networks:
      - djangonetwork
  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    # copy data of nginx.conf 
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/sites-available/example.conf
    networks:
      - main

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

networks:
  main:
  djangonetwork:
      driver: bridge
