class ErrorEnum:
    class HTTP:
        METHOD_NOT_ALLOWED = "HTTP_METHOD_NOT_ALLOWED"
        UNAUTHORIZED = "HTTP_UNAUTHORIZED"
        TOO_MANY_REQUESTS = "HTTP_TOO_MANY_REQUESTS"
        FORBIDDEN = "HTTP_FORBIDDEN"
        THROTTLED = "HTTP_THROTTLED"

    class Service:
        INVALID_USER_ID = "SERVICE_INVALID_USER_ID"
