# Generated by Django 4.1.3 on 2022-12-16 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="delay",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
